name: Build
on: workflow_dispatch

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
            - name: install yarn
              run: npm i -g yarn
            - name: install dependencies
              run: yarn
            - name: build
              run: yarn make
