name: Release
on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
            - name: install apt dependencies (ubuntu)
              if: ${{ matrix.os == ubuntu-latest }}
              run: sudo apt install -y flatpak flatpak-builder eu-strip
            - name: install yarn
              run: npm i -g yarn
            - name: install dependencies
              run: yarn
            - name: publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: yarn publish
